services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: crud-handling-exceptions
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: api
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d api" ]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  default:
    name: api-default-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.4.0/25

volumes:
  postgres: