services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: crud-handle
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: handledb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d handledb" ]
      interval: 2s
      timeout: 3s
      retries: 30
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  default:
    name: crud-api-default
    driver: bridge

volumes:
  postgres: